name: tensorflow-example
channels:
  - defaults
  - anaconda
dependencies:
  - python==3.6
  - pip:
    - pip
    - numpy
    - urllib3
    - tensorflow_addons
    - mlflow
    - tensorflow-gpu==2.2.0rc3
    - tensorflow_datasets
    - matplotlib
    - tensorflow_probability
    - sklearn
